name = "EasyHists"
uuid = "fadbf084-5835-4bcd-9457-830dc2bffdcd"
authors = ["Raye Kimmerer <kimmerer@mit.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
